### ISSUE TITLE
How can you compare rgb colors?

### ISSUE THREAD

**Issue by theRealProHacker** [shameempk/pyciede2000#1]
First, are you planning on implementing a function for rgb colors?

Secondly, if I have two rgb colors:
```python
BLACK=(0,0,0)
WHITE=(255,255,255)
```
How could I then easily compare them using another module? Do you have a tip? Is there maybe a function that easily converts between rgb and lab colors?
I know how to compare rgb colors in general from [Wikipedia](https://en.wikipedia.org/wiki/Color_difference), however I would like to calculate the ciede2000 difference.   
Thank you

**Comment by shameempk** [comment]
CIEDE2000 only works with Lab color space. You'll have to convert rgb to lab prior to this comparison. You can write your own function for it or use something like this: https://gist.github.com/bikz05/6fd21c812ef6ebac66e1
